# Generated by Django 4.2 on 2023-04-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('card', '0003_emailmodel_linkmodel_memomodel_phonemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='card_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='links', to='card.publiccardinfo'
            ),
        ),
    ]
