# Generated by Django 4.2 on 2023-04-18 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('card', '0004_emailmodel_order_linkmodel_order_phonemodel_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='card_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='card.publiccardinfo'
            ),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='card_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='card.publiccardinfo'
            ),
        ),
    ]
