# Generated by Django 4.2 on 2023-04-19 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('card', '0005_alter_emailmodel_card_id_alter_phonemodel_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='linkmodel',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='memomodel',
            old_name='card_id',
            new_name='card',
        ),
    ]
